/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Internal;

import App.controller.Class_Controller;
import App.controller.Course_Controller;
import App.controller.Student_Controller;
import App.mail.EmailValidation;
import App.model.tbl_Class;
import App.model.tbl_Course;
import App.model.tbl_Student;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Troanh
 */
public class Edit_Student extends javax.swing.JInternalFrame{

    /**
     * Creates new form Edit_Student
     */
    Connection conn;
    tbl_Student student;
    int id_teach;
    int role;
    EmailValidation ev = new EmailValidation();
    List<tbl_Class> LClass;

    public interface reload {
        public void load_table();
    };

    reload load;

    public Edit_Student(Connection conn, tbl_Student student, int id_teach, int role, reload load) {
        this.conn = conn;
        this.student = student;
        this.id_teach = id_teach;
        this.role = role;
        this.load = load;
        initComponents();
        get_Class("");
        set_Class();
        loadform();
    }

    private void get_Class(String check) {
        Class_Controller CC = new Class_Controller(conn);
        LClass = CC.select(check);
    }

    private void set_Class() {
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        for (tbl_Class c : LClass) {
            dcbm.addElement(c.getName());
        }
        Class_Student.setModel(dcbm);
        for (int i = 0; i < LClass.size(); i++) {
            tbl_Class c = LClass.get(i);
            if (c.getId() == student.getClass_ID()) {
                Class_Student.setSelectedIndex(i);
            }
        }
    }

    private void loadform() {
        MaSV.setText(student.getMasv());
        Name.setText(student.getName());
        Phone.setText(student.getPhone());
        Email.setText(student.getEmail());
        Address.setText(student.getAddress());
        try {
            DOB.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(student.getDOB()));
        } catch (ParseException ex) {
            Logger.getLogger(Edit_Student.class.getName()).log(Level.SEVERE, null, ex);
        }
        switch (student.getGender()) {
            case 1:
                Nam.doClick();
                break;
            case 2:
                Nu.doClick();
                break;
            default:
                unisex.doClick();
                break;
        }
        if (student.getStatus() == 1) {
            now.doClick();
        } else {
            unow.doClick();
        }
    }
    
        private boolean check_Masv(String masv) {
        Student_Controller SC = new Student_Controller(conn);
        List<tbl_Student> LS_check = SC.select(" WHERE MaSV != N'" + student.getMasv() + "'");
        boolean check = false;
        for (tbl_Student s : LS_check) {
            if (masv.equals(s.getMasv())){
                check = true;
            }
        }
        return check;
    }

    private boolean check_Mail(String email) {
        Student_Controller SC = new Student_Controller(conn);
        List<tbl_Student> LS_check = SC.select(" WHERE Email != N'" + student.getEmail() + "'");
        boolean check = false;
        for (tbl_Student s : LS_check) {
            if (email.equals(s.getEmail())){
                check = true;
            }
        }
        return check;
    }
    
    private boolean check_Phone(String phone) {
        Student_Controller SC = new Student_Controller(conn);
        List<tbl_Student> LS_check = SC.select(" WHERE Phone != N'" + student.getPhone()+ "'");
        boolean check = false;
        for (tbl_Student s : LS_check) {
            if (phone.equals(s.getPhone())){
                check = true;
            }
        }
        return check;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        unisex = new javax.swing.JRadioButton();
        Nam = new javax.swing.JRadioButton();
        Nu = new javax.swing.JRadioButton();
        Class_Student = new javax.swing.JComboBox<>();
        now = new javax.swing.JRadioButton();
        unow = new javax.swing.JRadioButton();
        DOB = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        Cancel = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        MaSV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Edit information");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel2.setText("Full Name");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel4.setText("Phone");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel7.setText("BoD");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel8.setText("Gender");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel9.setText("Class");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel10.setText("Status");

        Phone.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        Name.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        Email.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        Address.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        buttonGroup1.add(unisex);
        unisex.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        unisex.setText("Khác");
        unisex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unisexActionPerformed(evt);
            }
        });

        buttonGroup1.add(Nam);
        Nam.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Nam.setText("Nam");

        buttonGroup1.add(Nu);
        Nu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Nu.setText("Nữ");

        Class_Student.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Class_Student.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Class_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Class_StudentActionPerformed(evt);
            }
        });

        buttonGroup2.add(now);
        now.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        now.setText("Studying");

        buttonGroup2.add(unow);
        unow.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        unow.setText("Pause");
        unow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unowActionPerformed(evt);
            }
        });

        DOB.setDateFormatString("dd/MM/yyyy");
        DOB.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        Cancel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Update.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cancel)
                .addGap(18, 18, 18)
                .addComponent(Update)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(Update))
                .addContainerGap())
        );

        MaSV.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        MaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaSVActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel3.setText("Mã SV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Phone)
                                    .addComponent(Name)
                                    .addComponent(MaSV)
                                    .addComponent(Email)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(105, 105, 105)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Class_Student, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(now)
                                        .addGap(18, 18, 18)
                                        .addComponent(unow)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Nam)
                                        .addGap(36, 36, 36)
                                        .addComponent(Nu)
                                        .addGap(35, 35, 35)
                                        .addComponent(unisex)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE))
                                    .addComponent(Address)
                                    .addComponent(DOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Phone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Nam)
                    .addComponent(Nu)
                    .addComponent(unisex))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Class_Student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(now)
                    .addComponent(unow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        String regex_Phone = "^0[0-9]{9,10}$";
        int id = student.getId();
        String masv = MaSV.getText();
        String name = Name.getText();
        String phone = Phone.getText();
        String mail = Email.getText();
        String address = Address.getText();
        String birthday = new SimpleDateFormat("yyyy/MM/dd").format(DOB.getDate());
        int gender = 1;
        if (Nam.isSelected()) {
            gender = 1;
        } else if (Nu.isSelected()) {
            gender = 2;
        } else if (unisex.isSelected()) {
            gender = 3;
        }
        int class_choose = LClass.get(Class_Student.getSelectedIndex()).getId();
        int status;
        if (now.isSelected()) {
            status = 1;
        } else {
            status = 2;
        }
        if (check_Masv(masv)) {
            JOptionPane.showMessageDialog(null, "Mã SV bị trùng");
        } else if (check_Mail(mail)) {
            JOptionPane.showMessageDialog(null, "Email đã được sử dụng!");
        } else if (ev.isNotValidEmail(mail)) {
            JOptionPane.showMessageDialog(null, "Hãy kiểm tra lại email!");
        } else if (check_Phone(phone)) {
            JOptionPane.showMessageDialog(null, "SĐT đã được sử dụng!");
        } else if (name.length() == 0 || phone.length() == 0 || mail.length() == 0 || address.length() == 0 || masv.length() == 0) {
            JOptionPane.showMessageDialog(null, "Hãy điền đầy đủ thông tin");
        } else if (phone.length() > 13 || phone.length() < 8 || regex_Phone.matches(phone)) {
            JOptionPane.showMessageDialog(null, "SĐT phải từ 8 đến 13 số");
        } else {
            tbl_Student student_edit = new tbl_Student(id, masv, name, phone, mail, address, birthday, status, class_choose, "", gender);
            Student_Controller SC = new Student_Controller(conn);
            if (SC.update(student_edit)) {
                JOptionPane.showMessageDialog(null, "Bạn đã thay đổi thông tin sinh viên thành công!");
                load.load_table();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Đã có lỗi xảy ra");
            }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void unisexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unisexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unisexActionPerformed

    private void Class_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Class_StudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Class_StudentActionPerformed

    private void MaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaSVActionPerformed

    private void unowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JButton Cancel;
    private javax.swing.JComboBox<String> Class_Student;
    private com.toedter.calendar.JDateChooser DOB;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField MaSV;
    private javax.swing.JRadioButton Nam;
    private javax.swing.JTextField Name;
    private javax.swing.JRadioButton Nu;
    private javax.swing.JTextField Phone;
    private javax.swing.JButton Update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton now;
    private javax.swing.JRadioButton unisex;
    private javax.swing.JRadioButton unow;
    // End of variables declaration//GEN-END:variables
}
